// ── The catalog beyond the weight room ───────────────────────────────
// catalog.ts was authored around loaded resistance work, so an entire week
// of real training had nowhere to be logged: the jump rope that opens
// Monday, the 30-minute conversational run on Wednesday, every stretch in
// every cooldown, and the whole of Saturday. This file adds those.
//
// Two rules keep it honest:
//
// 1. Shares still sum to 1.0 and still name real muscles, so a hamstring
//    stretch is findable under hamstrings. But mobility, stretching and
//    recovery carry trainingEffect "target", and the aggregators skip them
//    — holding a couch stretch is not training your quads, and heat on the
//    map for it would be a lie the rest of the app then reasons from.
//
// 2. Nothing here invents precision it does not have. Interval and
//    steady-state work is logged as time at an intensity factor; the
//    factors are ordered relative to each other, not claimed as physiology.
import { expandExercise, type RawExercise } from "./catalog";
import type { Exercise } from "./types";

const EXTENDED_RAW: RawExercise[] = [
  // ══ PLYOMETRICS ══════════════════════════════════════════════════
  {
    id: "box-jump",
    name: "Box Jump",
    aliases: ["box jumps"],
    discipline: "plyometric",
    loadType: "bodyweight",
    limbsLoaded: 2,
    unilateral: false,
    leverageFactor: 0.9,
    muscles: [
      { muscle: "quads", share: 0.4 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "calves", share: 0.2 },
      { muscle: "hamstrings", share: 0.1 },
    ],
    equipment: ["none"],
    referenceVolume: 260,
    defaultRestSeconds: 120,
  },
  {
    id: "depth-jump",
    name: "Depth Jump",
    aliases: ["drop jump"],
    discipline: "plyometric",
    loadType: "bodyweight",
    limbsLoaded: 2,
    unilateral: false,
    leverageFactor: 1,
    muscles: [
      { muscle: "quads", share: 0.4 },
      { muscle: "calves", share: 0.3 },
      { muscle: "glutes", share: 0.2 },
      { muscle: "hamstrings", share: 0.1 },
    ],
    equipment: ["none"],
    referenceVolume: 280,
    defaultRestSeconds: 150,
  },
  {
    id: "crisscross-jump-squat",
    name: "Crisscross Jump Squat",
    aliases: ["criss cross jump squat", "scissor jump squat"],
    discipline: "plyometric",
    loadType: "bodyweight",
    limbsLoaded: 2,
    unilateral: false,
    leverageFactor: 0.85,
    muscles: [
      { muscle: "quads", share: 0.35 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "adductors", share: 0.2 },
      { muscle: "calves", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 220,
    defaultRestSeconds: 90,
  },
  {
    id: "tuck-jump",
    name: "Tuck Jump",
    aliases: [],
    discipline: "plyometric",
    loadType: "bodyweight",
    limbsLoaded: 2,
    unilateral: false,
    leverageFactor: 0.9,
    muscles: [
      { muscle: "quads", share: 0.35 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "abs", share: 0.2 },
      { muscle: "calves", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 230,
    defaultRestSeconds: 90,
  },
  {
    id: "lateral-bound",
    name: "Lateral Bound",
    aliases: ["skater jump"],
    discipline: "plyometric",
    loadType: "bodyweight",
    limbsLoaded: 1,
    unilateral: true,
    leverageFactor: 0.85,
    muscles: [
      { muscle: "glutes", share: 0.3 },
      { muscle: "quads", share: 0.25 },
      { muscle: "abductors", share: 0.25 },
      { muscle: "calves", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 200,
    defaultRestSeconds: 90,
  },
  {
    id: "medicine-ball-slam",
    name: "Medicine Ball Slam",
    aliases: ["ball slam", "med ball slam"],
    discipline: "plyometric",
    loadType: "dumbbell",
    limbsLoaded: 2,
    unilateral: false,
    muscles: [
      { muscle: "abs", share: 0.3 },
      { muscle: "back", share: 0.25 },
      { muscle: "shoulders", share: 0.25 },
      { muscle: "obliques", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 240,
    defaultRestSeconds: 90,
  },
  {
    id: "pogo-hop",
    name: "Pogo Hop",
    aliases: ["ankle hops"],
    discipline: "plyometric",
    loadType: "bodyweight",
    limbsLoaded: 2,
    unilateral: false,
    leverageFactor: 0.5,
    muscles: [
      { muscle: "calves", share: 0.7 },
      { muscle: "quads", share: 0.2 },
      { muscle: "glutes", share: 0.1 },
    ],
    equipment: ["none"],
    referenceVolume: 150,
    defaultRestSeconds: 60,
  },

  // ══ HIIT ═════════════════════════════════════════════════════════
  {
    id: "jump-rope",
    name: "Jump Rope",
    aliases: ["skipping", "skip rope", "rope skipping"],
    discipline: "hiit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 4,
    muscles: [
      { muscle: "calves", share: 0.45 },
      { muscle: "quads", share: 0.2 },
      { muscle: "forearms", share: 0.15 },
      { muscle: "abs", share: 0.1 },
      { muscle: "hamstrings", share: 0.1 },
    ],
    equipment: ["none"],
    referenceVolume: 400,
    defaultRestSeconds: 60,
  },
  {
    id: "double-under",
    name: "Double Under",
    aliases: ["doubleunders"],
    discipline: "hiit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 6,
    muscles: [
      { muscle: "calves", share: 0.45 },
      { muscle: "quads", share: 0.2 },
      { muscle: "forearms", share: 0.2 },
      { muscle: "abs", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 460,
    defaultRestSeconds: 90,
  },
  {
    id: "sprint-interval",
    name: "Sprint Interval",
    aliases: ["sprints", "hill sprints"],
    discipline: "hiit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 8,
    muscles: [
      { muscle: "quads", share: 0.3 },
      { muscle: "hamstrings", share: 0.3 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "calves", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 520,
    defaultRestSeconds: 120,
  },
  {
    id: "assault-bike-interval",
    name: "Assault Bike Interval",
    aliases: ["air bike", "fan bike"],
    discipline: "hiit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 7,
    muscles: [
      { muscle: "quads", share: 0.35 },
      { muscle: "shoulders", share: 0.2 },
      { muscle: "hamstrings", share: 0.2 },
      { muscle: "back", share: 0.15 },
      { muscle: "calves", share: 0.1 },
    ],
    equipment: ["machine"],
    referenceVolume: 480,
    defaultRestSeconds: 120,
  },
  {
    id: "battle-rope",
    name: "Battle Rope",
    aliases: ["battle ropes", "rope waves"],
    discipline: "hiit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 6,
    muscles: [
      { muscle: "shoulders", share: 0.35 },
      { muscle: "forearms", share: 0.2 },
      { muscle: "abs", share: 0.2 },
      { muscle: "back", share: 0.15 },
      { muscle: "biceps", share: 0.1 },
    ],
    equipment: ["none"],
    referenceVolume: 420,
    defaultRestSeconds: 90,
  },
  {
    id: "shuttle-run",
    name: "Shuttle Run",
    aliases: ["suicides", "beep test"],
    discipline: "hiit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 7,
    muscles: [
      { muscle: "quads", share: 0.35 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "hamstrings", share: 0.2 },
      { muscle: "calves", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 480,
    defaultRestSeconds: 120,
  },

  // ══ LIIT / steady state ══════════════════════════════════════════
  {
    id: "easy-run",
    name: "Easy Run",
    aliases: ["running", "jog", "conversational run", "zone 2 run"],
    discipline: "liit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 2,
    muscles: [
      { muscle: "quads", share: 0.35 },
      { muscle: "hamstrings", share: 0.25 },
      { muscle: "calves", share: 0.25 },
      { muscle: "glutes", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 260,
    defaultRestSeconds: 0,
  },
  {
    id: "brisk-walk",
    name: "Brisk Walk",
    aliases: ["walking", "walk", "ruck-free walk"],
    discipline: "liit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "quads", share: 0.3 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "calves", share: 0.25 },
      { muscle: "hamstrings", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 180,
    defaultRestSeconds: 0,
  },
  {
    id: "incline-treadmill-walk",
    name: "Incline Treadmill Walk",
    aliases: ["incline walk", "stairmaster walk"],
    discipline: "liit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 2,
    muscles: [
      { muscle: "glutes", share: 0.35 },
      { muscle: "quads", share: 0.25 },
      { muscle: "hamstrings", share: 0.2 },
      { muscle: "calves", share: 0.2 },
    ],
    equipment: ["machine"],
    referenceVolume: 220,
    defaultRestSeconds: 0,
  },
  {
    id: "steady-cycle",
    name: "Steady Cycle",
    aliases: ["cycling", "stationary bike"],
    discipline: "liit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 2,
    muscles: [
      { muscle: "quads", share: 0.5 },
      { muscle: "hamstrings", share: 0.2 },
      { muscle: "glutes", share: 0.15 },
      { muscle: "calves", share: 0.15 },
    ],
    equipment: ["machine"],
    referenceVolume: 220,
    defaultRestSeconds: 0,
  },
  {
    id: "steady-row",
    name: "Steady Row",
    aliases: ["rowing machine", "erg"],
    discipline: "liit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 3,
    muscles: [
      { muscle: "back", share: 0.25 },
      { muscle: "quads", share: 0.25 },
      { muscle: "hamstrings", share: 0.15 },
      { muscle: "biceps", share: 0.15 },
      { muscle: "lowerBack", share: 0.1 },
      { muscle: "forearms", share: 0.1 },
    ],
    equipment: ["machine"],
    referenceVolume: 280,
    defaultRestSeconds: 0,
  },
  {
    id: "swim-laps",
    name: "Swim Laps",
    aliases: ["swimming", "freestyle swim"],
    discipline: "liit",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 3,
    muscles: [
      { muscle: "back", share: 0.3 },
      { muscle: "chest", share: 0.2 },
      { muscle: "shoulders", share: 0.2 },
      { muscle: "triceps", share: 0.15 },
      { muscle: "abs", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 260,
    defaultRestSeconds: 0,
  },

  // ══ HYBRID ATHLETICISM ═══════════════════════════════════════════
  {
    id: "sandbag-carry",
    name: "Sandbag Carry",
    aliases: ["bear hug carry"],
    discipline: "hybrid",
    loadType: "distance",
    limbsLoaded: 1,
    unilateral: false,
    leverageFactor: 1,
    muscles: [
      { muscle: "abs", share: 0.25 },
      { muscle: "lowerBack", share: 0.2 },
      { muscle: "quads", share: 0.2 },
      { muscle: "traps", share: 0.2 },
      { muscle: "forearms", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 900,
    defaultRestSeconds: 150,
  },
  {
    id: "sled-drag",
    name: "Sled Drag",
    aliases: ["backwards sled drag"],
    discipline: "hybrid",
    loadType: "distance",
    limbsLoaded: 1,
    unilateral: false,
    leverageFactor: 1,
    muscles: [
      { muscle: "quads", share: 0.4 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "hamstrings", share: 0.2 },
      { muscle: "calves", share: 0.15 },
    ],
    equipment: ["machine"],
    referenceVolume: 900,
    defaultRestSeconds: 150,
  },
  {
    id: "kettlebell-clean-and-jerk",
    name: "Kettlebell Clean and Jerk",
    aliases: ["kb clean and jerk"],
    discipline: "hybrid",
    loadType: "dumbbell",
    limbsLoaded: 1,
    unilateral: true,
    muscles: [
      { muscle: "shoulders", share: 0.25 },
      { muscle: "glutes", share: 0.2 },
      { muscle: "quads", share: 0.2 },
      { muscle: "traps", share: 0.2 },
      { muscle: "abs", share: 0.15 },
    ],
    equipment: ["kettlebell"],
    referenceVolume: 700,
    defaultRestSeconds: 150,
  },
  {
    id: "turkish-get-up",
    name: "Turkish Get-Up",
    aliases: ["tgu", "get up"],
    discipline: "hybrid",
    loadType: "dumbbell",
    limbsLoaded: 1,
    unilateral: true,
    muscles: [
      { muscle: "shoulders", share: 0.25 },
      { muscle: "abs", share: 0.25 },
      { muscle: "obliques", share: 0.2 },
      { muscle: "quads", share: 0.15 },
      { muscle: "glutes", share: 0.15 },
    ],
    equipment: ["kettlebell"],
    referenceVolume: 620,
    defaultRestSeconds: 150,
  },
  {
    id: "thruster",
    name: "Thruster",
    aliases: ["barbell thruster"],
    discipline: "hybrid",
    loadType: "barbell",
    limbsLoaded: 1,
    unilateral: false,
    muscles: [
      { muscle: "quads", share: 0.3 },
      { muscle: "shoulders", share: 0.3 },
      { muscle: "glutes", share: 0.2 },
      { muscle: "triceps", share: 0.2 },
    ],
    equipment: ["barbell"],
    referenceVolume: 900,
    defaultRestSeconds: 180,
  },
  {
    id: "wall-ball",
    name: "Wall Ball",
    aliases: ["wall balls", "wall ball shot"],
    discipline: "hybrid",
    loadType: "dumbbell",
    limbsLoaded: 2,
    unilateral: false,
    muscles: [
      { muscle: "quads", share: 0.3 },
      { muscle: "shoulders", share: 0.3 },
      { muscle: "glutes", share: 0.2 },
      { muscle: "triceps", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 520,
    defaultRestSeconds: 120,
  },
  {
    id: "ruck-march",
    name: "Ruck March",
    aliases: ["rucking", "weighted walk"],
    discipline: "hybrid",
    loadType: "distance",
    limbsLoaded: 1,
    unilateral: false,
    leverageFactor: 1,
    muscles: [
      { muscle: "quads", share: 0.25 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "calves", share: 0.2 },
      { muscle: "lowerBack", share: 0.15 },
      { muscle: "traps", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 1000,
    defaultRestSeconds: 0,
  },

  // ══ CALISTHENICS — skill and holds ═══════════════════════════════
  {
    id: "handstand-hold",
    name: "Handstand Hold",
    aliases: ["handstand practice", "handstand"],
    discipline: "calisthenics",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 6,
    muscles: [
      { muscle: "shoulders", share: 0.4 },
      { muscle: "triceps", share: 0.2 },
      { muscle: "abs", share: 0.2 },
      { muscle: "forearms", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 420,
    defaultRestSeconds: 120,
  },
  {
    id: "l-sit",
    name: "L-Sit",
    aliases: ["l sit", "l-sit progression"],
    discipline: "calisthenics",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 7,
    muscles: [
      { muscle: "abs", share: 0.4 },
      { muscle: "quads", share: 0.25 },
      { muscle: "triceps", share: 0.2 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["dip-bar"],
    referenceVolume: 400,
    defaultRestSeconds: 120,
  },
  {
    id: "tuck-planche",
    name: "Tuck Planche",
    aliases: ["planche progression"],
    discipline: "calisthenics",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 8,
    muscles: [
      { muscle: "shoulders", share: 0.35 },
      { muscle: "abs", share: 0.25 },
      { muscle: "chest", share: 0.2 },
      { muscle: "forearms", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 440,
    defaultRestSeconds: 150,
  },
  {
    id: "front-lever-progression",
    name: "Front Lever Progression",
    aliases: ["front lever", "tuck front lever"],
    discipline: "calisthenics",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 8,
    muscles: [
      { muscle: "back", share: 0.4 },
      { muscle: "abs", share: 0.3 },
      { muscle: "shoulders", share: 0.2 },
      { muscle: "forearms", share: 0.1 },
    ],
    equipment: ["pull-up-bar"],
    referenceVolume: 460,
    defaultRestSeconds: 150,
  },
  {
    id: "scapular-pull-up",
    name: "Scapular Pull-up",
    aliases: ["scap pull-up", "scapular control"],
    discipline: "calisthenics",
    loadType: "bodyweight",
    limbsLoaded: 1,
    unilateral: false,
    leverageFactor: 0.9,
    muscles: [
      { muscle: "back", share: 0.5 },
      { muscle: "traps", share: 0.35 },
      { muscle: "forearms", share: 0.15 },
    ],
    equipment: ["pull-up-bar"],
    referenceVolume: 240,
    defaultRestSeconds: 60,
  },
  {
    id: "pushup-hold",
    name: "Push-up Hold",
    aliases: ["bottom push-up hold", "push up hold"],
    discipline: "calisthenics",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 5,
    muscles: [
      { muscle: "chest", share: 0.4 },
      { muscle: "triceps", share: 0.3 },
      { muscle: "shoulders", share: 0.2 },
      { muscle: "abs", share: 0.1 },
    ],
    equipment: ["none"],
    referenceVolume: 300,
    defaultRestSeconds: 90,
  },
  {
    id: "lying-leg-raise",
    name: "Lying Leg Raise",
    aliases: ["leg raises", "floor leg raise"],
    discipline: "calisthenics",
    loadType: "bodyweight",
    limbsLoaded: 2,
    unilateral: false,
    leverageFactor: 0.35,
    muscles: [
      { muscle: "abs", share: 0.75 },
      { muscle: "obliques", share: 0.15 },
      { muscle: "quads", share: 0.1 },
    ],
    equipment: ["none"],
    referenceVolume: 180,
    defaultRestSeconds: 60,
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    aliases: ["cross-hack squat", "machine hack squat"],
    discipline: "strength",
    loadType: "machine",
    limbsLoaded: 1,
    unilateral: false,
    muscles: [
      { muscle: "quads", share: 0.6 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "hamstrings", share: 0.15 },
    ],
    equipment: ["machine"],
    referenceVolume: 1400,
    defaultRestSeconds: 180,
  },

  // ══ MOBILITY — active range of motion ════════════════════════════
  {
    id: "deep-squat-hold",
    name: "Deep Squat Hold",
    aliases: ["asian squat", "malasana", "deep squat"],
    discipline: "mobility",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "adductors", share: 0.35 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "calves", share: 0.2 },
      { muscle: "lowerBack", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 100,
    defaultRestSeconds: 30,
  },
  {
    id: "ankle-rotation",
    name: "Ankle Rotation",
    aliases: ["ankle circles", "ankle rotations"],
    discipline: "mobility",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [{ muscle: "calves", share: 1 }],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 15,
  },
  {
    id: "thoracic-rotation",
    name: "Thoracic Rotation",
    aliases: ["t-spine rotation", "thoracic rotations", "open book"],
    discipline: "mobility",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "obliques", share: 0.4 },
      { muscle: "back", share: 0.35 },
      { muscle: "lowerBack", share: 0.25 },
    ],
    equipment: ["none"],
    referenceVolume: 70,
    defaultRestSeconds: 15,
  },
  {
    id: "hip-circle",
    name: "Hip Circle",
    aliases: ["hip circles", "90/90 transition"],
    discipline: "mobility",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "glutes", share: 0.4 },
      { muscle: "abductors", share: 0.35 },
      { muscle: "adductors", share: 0.25 },
    ],
    equipment: ["none"],
    referenceVolume: 70,
    defaultRestSeconds: 15,
  },
  {
    id: "shoulder-dislocate",
    name: "Shoulder Dislocate",
    aliases: ["band pass-through", "shoulder pass through"],
    discipline: "mobility",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "shoulders", share: 0.5 },
      { muscle: "chest", share: 0.3 },
      { muscle: "traps", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 70,
    defaultRestSeconds: 15,
  },
  {
    id: "cat-cow",
    name: "Cat-Cow",
    aliases: ["cat camel", "spine stretch"],
    discipline: "mobility",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "lowerBack", share: 0.5 },
      { muscle: "abs", share: 0.3 },
      { muscle: "back", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 70,
    defaultRestSeconds: 15,
  },
  {
    id: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    aliases: ["compound stretch", "lunge with rotation"],
    discipline: "mobility",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "adductors", share: 0.3 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "obliques", share: 0.25 },
      { muscle: "hamstrings", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 90,
    defaultRestSeconds: 20,
  },
  {
    id: "scapular-wall-slide",
    name: "Scapular Wall Slide",
    aliases: ["wall slides", "wall angel"],
    discipline: "mobility",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "traps", share: 0.5 },
      { muscle: "shoulders", share: 0.3 },
      { muscle: "back", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 70,
    defaultRestSeconds: 15,
  },

  // ══ STRETCHING — passive lengthening ═════════════════════════════
  {
    id: "couch-stretch",
    name: "Couch Stretch",
    aliases: ["quad hip flexor stretch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "quads", share: 0.7 },
      { muscle: "glutes", share: 0.3 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "forward-fold",
    name: "Forward Fold",
    aliases: ["standing hamstring stretch", "toe touch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "hamstrings", share: 0.6 },
      { muscle: "lowerBack", share: 0.25 },
      { muscle: "calves", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "scissor-stretch",
    name: "Scissor Stretch",
    aliases: ["scissor hamstring stretch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "hamstrings", share: 0.6 },
      { muscle: "adductors", share: 0.25 },
      { muscle: "calves", share: 0.15 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "doorway-pec-stretch",
    name: "Doorway Pec Stretch",
    aliases: ["chest stretch", "doorway chest stretch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "chest", share: 0.75 },
      { muscle: "shoulders", share: 0.25 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "cross-body-shoulder-stretch",
    name: "Cross-Body Shoulder Stretch",
    aliases: ["cross body stretch", "rear delt stretch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "shoulders", share: 0.7 },
      { muscle: "back", share: 0.3 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "overhead-triceps-stretch",
    name: "Overhead Triceps Stretch",
    aliases: ["triceps overhead stretch", "triceps stretch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "triceps", share: 0.75 },
      { muscle: "back", share: 0.25 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "cobra-stretch",
    name: "Cobra Stretch",
    aliases: ["upward dog", "cobra"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "abs", share: 0.5 },
      { muscle: "chest", share: 0.3 },
      { muscle: "lowerBack", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "childs-pose",
    name: "Child's Pose",
    aliases: ["childs pose", "balasana"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "lowerBack", share: 0.45 },
      { muscle: "back", share: 0.35 },
      { muscle: "glutes", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "pigeon-pose",
    name: "Pigeon Pose",
    aliases: ["glute stretch", "figure four stretch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "glutes", share: 0.65 },
      { muscle: "abductors", share: 0.35 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "calf-wall-stretch",
    name: "Calf Wall Stretch",
    aliases: ["gastroc stretch", "calf stretch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [{ muscle: "calves", share: 1 }],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },
  {
    id: "seated-straddle",
    name: "Seated Straddle",
    aliases: ["middle split stretch", "straddle stretch"],
    discipline: "stretching",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "adductors", share: 0.6 },
      { muscle: "hamstrings", share: 0.4 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 10,
  },

  // ══ RECOVERY ═════════════════════════════════════════════════════
  {
    id: "foam-roll-quads",
    name: "Foam Roll — Quads",
    aliases: ["quad foam rolling"],
    discipline: "recovery",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: true,
    intensityFactor: 1,
    muscles: [
      { muscle: "quads", share: 0.8 },
      { muscle: "adductors", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 0,
  },
  {
    id: "foam-roll-back",
    name: "Foam Roll — Upper Back",
    aliases: ["thoracic foam rolling"],
    discipline: "recovery",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "back", share: 0.6 },
      { muscle: "traps", share: 0.4 },
    ],
    equipment: ["none"],
    referenceVolume: 60,
    defaultRestSeconds: 0,
  },
  {
    id: "nasal-breathing-drill",
    name: "Breathing Drill",
    aliases: ["box breathing", "diaphragmatic breathing"],
    discipline: "recovery",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 1,
    muscles: [
      { muscle: "abs", share: 0.7 },
      { muscle: "obliques", share: 0.3 },
    ],
    equipment: ["none"],
    referenceVolume: 50,
    defaultRestSeconds: 0,
  },
  {
    id: "crawling",
    name: "Crawling",
    aliases: ["baby crawl", "leopard crawl"],
    discipline: "recovery",
    loadType: "time",
    limbsLoaded: 1,
    unilateral: false,
    intensityFactor: 2,
    muscles: [
      { muscle: "shoulders", share: 0.3 },
      { muscle: "abs", share: 0.3 },
      { muscle: "quads", share: 0.2 },
      { muscle: "obliques", share: 0.2 },
    ],
    equipment: ["none"],
    referenceVolume: 120,
    defaultRestSeconds: 30,
  },
];

export const EXTENDED_CATALOG: Exercise[] = EXTENDED_RAW.map(expandExercise);
