// Seed trades — all fields use judasSwing (correct property name)
export const SEED_TRADES = [
  {
    id: "t001", date: "2026-06-26", time: "09:52", instrument: "NQ1!", direction: "LONG",
    session: "NY Open", models: ["Fair Value Gap (FVG)", "Order Block (OB)"],
    marketStructure: "MSS", htfBias: "Bullish", premiumDiscount: "Discount Array",
    liquidityTarget: "SSL (Sell Side Liq)", smtDivergence: false, smtPair: "",
    po3Phase: "Accumulation", htfConfirmed: ["Daily", "Weekly"],
    intermediateContext: ["1H"], entryTimeframe: "5M",
    ictMacro: "m_950", silverBullet: "", mmModel: "Buy Program",
    dealingRangeH: "21520", dealingRangeL: "21440",
    dol: "SSL (Sell Side Liq)", judasSwing: false,
    entryPrice: 21480, stopPrice: 21455, targetPrice: 21535, contracts: 1, tvUrl: "",
    stopDistance: 25, projectedRR: 2.2, riskAmount: 500, riskPercent: 0.83,
    checklist: [true, true, true, true, true, true, true], checklistScore: 7,
    exitPrice: 21532, hasPartial: false, partialExitPrice: "", partialSize: "0.5", remainingExitPrice: "",
    outcome: "WIN", grade: "A+", targetReached: true,
    entryQuality: "Ideal (displaced confirmation)", exitQuality: "Full target reached",
    psychologyTag: "Disciplined", executionScore: 9,
    notes: "ICT 9:50 Macro opened window. SSL swept at 21,455, immediate displacement through FVG at 21,470. OB confluence. W/D bias strongly bullish.",
    lessons: "Trust macro windows. 9:50 macro is the highest probability NY entry window. OB+FVG confluence = A+.",
    slippage: 0, status: "CLOSED", actualRR: 2.1, pnl: 1050, createdAt: "2026-06-26T09:52:00",
  },
  {
    id: "t002", date: "2026-06-25", time: "10:15", instrument: "ES1!", direction: "SHORT",
    session: "NY Open", models: ["Order Block (OB)", "Displacement"],
    marketStructure: "BOS", htfBias: "Bearish", premiumDiscount: "Premium Array",
    liquidityTarget: "BSL (Buy Side Liq)", smtDivergence: true, smtPair: "NQ1!",
    po3Phase: "Distribution / Delivery", htfConfirmed: ["Daily"],
    intermediateContext: ["4H", "1H"], entryTimeframe: "5M",
    ictMacro: "", silverBullet: "", mmModel: "Sell Program",
    dealingRangeH: "5830", dealingRangeL: "5800",
    dol: "BSL (Buy Side Liq)", judasSwing: true,
    entryPrice: 5820, stopPrice: 5830, targetPrice: 5800, contracts: 1, tvUrl: "",
    stopDistance: 10, projectedRR: 2.0, riskAmount: 500, riskPercent: 0.5,
    checklist: [true, true, true, true, true, true, true], checklistScore: 7,
    exitPrice: 5808, hasPartial: false, partialExitPrice: "", partialSize: "0.5", remainingExitPrice: "",
    outcome: "WIN", grade: "A", targetReached: false,
    entryQuality: "On-point", exitQuality: "Early exit (fear)",
    psychologyTag: "Patient", executionScore: 8,
    notes: "SMT divergence ES vs NQ. Judas swing swept BSL before reversal. OB in premium confluence.",
    lessons: "Left 0.8R on table. ES hit target 40 min later. Trust the target once structure is delivered.",
    slippage: 1, status: "CLOSED", actualRR: 1.2, pnl: 600, createdAt: "2026-06-25T10:15:00",
  },
  {
    id: "t003", date: "2026-06-24", time: "09:35", instrument: "NQ1!", direction: "LONG",
    session: "NY Open", models: ["Fair Value Gap (FVG)"],
    marketStructure: "MSS", htfBias: "Bullish", premiumDiscount: "Discount Array",
    liquidityTarget: "EQL", smtDivergence: false, smtPair: "",
    po3Phase: "", htfConfirmed: ["Daily"], intermediateContext: ["1H"], entryTimeframe: "1M",
    ictMacro: "", silverBullet: "", mmModel: "None",
    dealingRangeH: "", dealingRangeL: "", dol: "", judasSwing: false,
    entryPrice: 21350, stopPrice: 21320, targetPrice: 21420, contracts: 1, tvUrl: "",
    stopDistance: 30, projectedRR: 2.3, riskAmount: 600, riskPercent: 1.0,
    checklist: [true, true, true, true, true, false, false], checklistScore: 5,
    exitPrice: 21320, hasPartial: false, partialExitPrice: "", partialSize: "0.5", remainingExitPrice: "",
    outcome: "LOSS", grade: "B", targetReached: false,
    entryQuality: "Slightly early", exitQuality: "Stopped out correctly",
    psychologyTag: "FOMO", executionScore: 4,
    notes: "News at 9:30 disrupted. Entered FVG before displacement confirmed. Checklist items 6+7 failed.",
    lessons: "CHECKLIST IS NON-NEGOTIABLE. Did not check news. FOMO entry = -$600 tuition.",
    slippage: 2, status: "CLOSED", actualRR: -1, pnl: -600, createdAt: "2026-06-24T09:35:00",
  },
  {
    id: "t004", date: "2026-06-23", time: "10:05", instrument: "NQ1!", direction: "SHORT",
    session: "NY Open", models: ["Breaker Block", "Fair Value Gap (FVG)", "Displacement"],
    marketStructure: "BOS", htfBias: "Bearish", premiumDiscount: "Premium Array",
    liquidityTarget: "BSL (Buy Side Liq)", smtDivergence: false, smtPair: "",
    po3Phase: "Manipulation / Judas Swing", htfConfirmed: ["Weekly", "Daily"],
    intermediateContext: ["4H", "1H"], entryTimeframe: "5M",
    ictMacro: "m_950", silverBullet: "", mmModel: "Sell Program",
    dealingRangeH: "21540", dealingRangeL: "21450",
    dol: "BSL (Buy Side Liq)", judasSwing: true,
    entryPrice: 21510, stopPrice: 21532, targetPrice: 21458, contracts: 1, tvUrl: "",
    stopDistance: 22, projectedRR: 2.4, riskAmount: 440, riskPercent: 0.73,
    checklist: [true, true, true, true, true, true, true], checklistScore: 7,
    exitPrice: "", hasPartial: true, partialExitPrice: "21490", partialSize: "0.5", remainingExitPrice: "21460",
    outcome: "WIN", grade: "A+", targetReached: true,
    entryQuality: "Ideal (displaced confirmation)", exitQuality: "Took partials — held runner",
    psychologyTag: "Disciplined", executionScore: 9,
    notes: "Breaker block after displacement. Judas swing swept BSL. Triple model confluence. A+ sell program template.",
    lessons: "Judas sweep of BSL → BB/FVG in premium → displacement → entry on CE. Partials gave breathing room.",
    slippage: 0, status: "CLOSED", actualRR: 2.4, pnl: 1020, createdAt: "2026-06-23T10:05:00",
  },
  {
    id: "t005", date: "2026-06-20", time: "14:10", instrument: "ES1!", direction: "LONG",
    session: "NY PM", models: ["OTE (62–79% Fib)", "Fair Value Gap (FVG)"],
    marketStructure: "MSS", htfBias: "Bullish", premiumDiscount: "Discount Array",
    liquidityTarget: "SSL (Sell Side Liq)", smtDivergence: false, smtPair: "",
    po3Phase: "Accumulation", htfConfirmed: ["Daily"], intermediateContext: ["1H"], entryTimeframe: "15M",
    ictMacro: "m_210", silverBullet: "sb_14", mmModel: "Buy Program",
    dealingRangeH: "5820", dealingRangeL: "5795",
    dol: "SSL (Sell Side Liq)", judasSwing: false,
    entryPrice: 5800, stopPrice: 5788, targetPrice: 5824, contracts: 1, tvUrl: "",
    stopDistance: 12, projectedRR: 2.0, riskAmount: 600, riskPercent: 0.8,
    checklist: [true, true, true, true, true, true, true], checklistScore: 7,
    exitPrice: 5800, hasPartial: false, partialExitPrice: "", partialSize: "0.5", remainingExitPrice: "",
    outcome: "BE", grade: "B+", targetReached: false,
    entryQuality: "On-point", exitQuality: "Moved stop to BE too early",
    psychologyTag: "Anxious", executionScore: 6,
    notes: "2PM Silver Bullet + 2:10 Macro confluence. Valid OTE at 62% into FVG. Anxiety caused premature BE move.",
    lessons: "SM hunted BE stops before target delivery. Anxiety = money left on table. 2R winner turned BE.",
    slippage: 0, status: "CLOSED", actualRR: 0, pnl: 0, createdAt: "2026-06-20T14:10:00",
  },
];
