import type { Exercise } from "./types.js";

// ~80 seeded exercises. leverageFactor is required for bodyweight /
// weighted_bodyweight / assisted movements; intensityFactor is required for
// time / distance movements. referenceVolume is the volume a novice produces
// in one solid working set for that exercise — see spec §4.2.
export const EXERCISE_CATALOG: Exercise[] = [
  // ---- Chest ----
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    aliases: ["bench press", "bb bench"],
    loadType: "barbell",
    muscles: [
      { muscle: "chest", share: 0.6 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["barbell", "bench"],
    unilateral: false,
    referenceVolume: 320,
  },
  {
    id: "incline-barbell-bench-press",
    name: "Incline Barbell Bench Press",
    aliases: ["incline bench"],
    loadType: "barbell",
    muscles: [
      { muscle: "chest", share: 0.55 },
      { muscle: "shoulders", share: 0.25 },
      { muscle: "triceps", share: 0.2 },
    ],
    equipment: ["barbell", "bench"],
    unilateral: false,
    referenceVolume: 280,
  },
  {
    id: "decline-barbell-bench-press",
    name: "Decline Barbell Bench Press",
    aliases: ["decline bench"],
    loadType: "barbell",
    muscles: [
      { muscle: "chest", share: 0.65 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "shoulders", share: 0.1 },
    ],
    equipment: ["barbell", "bench"],
    unilateral: false,
    referenceVolume: 320,
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    aliases: ["db bench"],
    loadType: "dumbbell",
    muscles: [
      { muscle: "chest", share: 0.58 },
      { muscle: "triceps", share: 0.24 },
      { muscle: "shoulders", share: 0.18 },
    ],
    equipment: ["dumbbell", "bench"],
    unilateral: false,
    referenceVolume: 240,
  },
  {
    id: "incline-dumbbell-bench-press",
    name: "Incline Dumbbell Bench Press",
    aliases: ["incline db bench"],
    loadType: "dumbbell",
    muscles: [
      { muscle: "chest", share: 0.55 },
      { muscle: "shoulders", share: 0.25 },
      { muscle: "triceps", share: 0.2 },
    ],
    equipment: ["dumbbell", "bench"],
    unilateral: false,
    referenceVolume: 220,
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    aliases: ["chest press machine"],
    loadType: "machine",
    muscles: [
      { muscle: "chest", share: 0.62 },
      { muscle: "triceps", share: 0.23 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 300,
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    aliases: ["cable crossover"],
    loadType: "cable",
    muscles: [
      { muscle: "chest", share: 0.8 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["cable"],
    unilateral: false,
    referenceVolume: 180,
  },
  {
    id: "pushup",
    name: "Push-up",
    aliases: ["press up", "pushups"],
    loadType: "bodyweight",
    leverageFactor: 0.64,
    muscles: [
      { muscle: "chest", share: 0.55 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 2000,
  },
  {
    id: "incline-pushup",
    name: "Incline Push-up",
    aliases: ["incline pushups"],
    loadType: "bodyweight",
    leverageFactor: 0.55,
    muscles: [
      { muscle: "chest", share: 0.5 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "shoulders", share: 0.25 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 2200,
  },
  {
    id: "dip",
    name: "Dip",
    aliases: ["chest dip", "triceps dip"],
    loadType: "bodyweight",
    leverageFactor: 0.95,
    muscles: [
      { muscle: "chest", share: 0.4 },
      { muscle: "triceps", share: 0.4 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["dip-bar"],
    unilateral: false,
    referenceVolume: 850,
  },

  // ---- Back ----
  {
    id: "deadlift",
    name: "Deadlift",
    aliases: ["conventional deadlift"],
    loadType: "barbell",
    muscles: [
      { muscle: "back", share: 0.3 },
      { muscle: "lowerBack", share: 0.2 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "hamstrings", share: 0.2 },
      { muscle: "traps", share: 0.05 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 400,
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    aliases: ["bent over row"],
    loadType: "barbell",
    muscles: [
      { muscle: "back", share: 0.55 },
      { muscle: "lowerBack", share: 0.15 },
      { muscle: "biceps", share: 0.15 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 350,
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    aliases: [],
    loadType: "machine",
    muscles: [
      { muscle: "back", share: 0.6 },
      { muscle: "biceps", share: 0.2 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 320,
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    aliases: [],
    loadType: "cable",
    muscles: [
      { muscle: "back", share: 0.55 },
      { muscle: "biceps", share: 0.25 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["cable"],
    unilateral: false,
    referenceVolume: 300,
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    aliases: [],
    loadType: "cable",
    muscles: [
      { muscle: "back", share: 0.65 },
      { muscle: "biceps", share: 0.25 },
      { muscle: "shoulders", share: 0.1 },
    ],
    equipment: ["cable"],
    unilateral: false,
    referenceVolume: 300,
  },
  {
    id: "pull-up",
    name: "Pull-up",
    aliases: ["pullups"],
    loadType: "bodyweight",
    leverageFactor: 1.0,
    muscles: [
      { muscle: "back", share: 0.55 },
      { muscle: "biceps", share: 0.3 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["pull-up-bar"],
    unilateral: false,
    referenceVolume: 700,
  },
  {
    id: "chin-up",
    name: "Chin-up",
    aliases: ["chinups"],
    loadType: "bodyweight",
    leverageFactor: 1.0,
    muscles: [
      { muscle: "back", share: 0.45 },
      { muscle: "biceps", share: 0.4 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["pull-up-bar"],
    unilateral: false,
    referenceVolume: 650,
  },
  {
    id: "weighted-pull-up",
    name: "Weighted Pull-up",
    aliases: [],
    loadType: "weighted_bodyweight",
    leverageFactor: 1.0,
    muscles: [
      { muscle: "back", share: 0.55 },
      { muscle: "biceps", share: 0.3 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["pull-up-bar", "bar"],
    unilateral: false,
    referenceVolume: 750,
  },
  {
    id: "assisted-pull-up",
    name: "Assisted Pull-up",
    aliases: [],
    loadType: "assisted",
    leverageFactor: 1.0,
    muscles: [
      { muscle: "back", share: 0.55 },
      { muscle: "biceps", share: 0.3 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["pull-up-bar", "machine"],
    unilateral: false,
    referenceVolume: 650,
  },
  {
    id: "inverted-row",
    name: "Inverted Row",
    aliases: ["bodyweight row"],
    loadType: "bodyweight",
    leverageFactor: 0.6,
    muscles: [
      { muscle: "back", share: 0.55 },
      { muscle: "biceps", share: 0.25 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["bar"],
    unilateral: false,
    referenceVolume: 1100,
  },
  {
    id: "single-arm-dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    aliases: ["db row"],
    loadType: "dumbbell",
    muscles: [
      { muscle: "back", share: 0.55 },
      { muscle: "biceps", share: 0.2 },
      { muscle: "shoulders", share: 0.15 },
      { muscle: "lowerBack", share: 0.1 },
    ],
    equipment: ["dumbbell", "bench"],
    unilateral: true,
    referenceVolume: 720,
  },
  {
    id: "good-morning",
    name: "Good Morning",
    aliases: [],
    loadType: "barbell",
    muscles: [
      { muscle: "hamstrings", share: 0.4 },
      { muscle: "lowerBack", share: 0.35 },
      { muscle: "glutes", share: 0.25 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 200,
  },
  {
    id: "back-extension",
    name: "Back Extension",
    aliases: ["hyperextension"],
    loadType: "bodyweight",
    leverageFactor: 0.4,
    muscles: [
      { muscle: "lowerBack", share: 0.55 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "hamstrings", share: 0.15 },
    ],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 900,
  },
  {
    id: "superman",
    name: "Superman",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.3,
    muscles: [
      { muscle: "lowerBack", share: 0.6 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "traps", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1000,
  },

  // ---- Shoulders ----
  {
    id: "overhead-press",
    name: "Overhead Press",
    aliases: ["ohp", "military press"],
    loadType: "barbell",
    muscles: [
      { muscle: "shoulders", share: 0.65 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "traps", share: 0.1 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 220,
  },
  {
    id: "seated-dumbbell-press",
    name: "Seated Dumbbell Press",
    aliases: ["db shoulder press"],
    loadType: "dumbbell",
    muscles: [
      { muscle: "shoulders", share: 0.65 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "traps", share: 0.1 },
    ],
    equipment: ["dumbbell"],
    unilateral: false,
    referenceVolume: 200,
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    aliases: [],
    loadType: "machine",
    muscles: [
      { muscle: "shoulders", share: 0.65 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "traps", share: 0.1 },
    ],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 240,
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    aliases: ["side raise"],
    loadType: "dumbbell",
    muscles: [
      { muscle: "shoulders", share: 0.9 },
      { muscle: "traps", share: 0.1 },
    ],
    equipment: ["dumbbell"],
    unilateral: false,
    referenceVolume: 140,
  },
  {
    id: "pike-pushup",
    name: "Pike Push-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.6,
    muscles: [
      { muscle: "shoulders", share: 0.55 },
      { muscle: "triceps", share: 0.3 },
      { muscle: "chest", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1400,
  },
  {
    id: "handstand-pushup",
    name: "Handstand Push-up",
    aliases: ["hspu"],
    loadType: "bodyweight",
    leverageFactor: 0.9,
    muscles: [
      { muscle: "shoulders", share: 0.6 },
      { muscle: "triceps", share: 0.3 },
      { muscle: "chest", share: 0.1 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 500,
  },

  // ---- Traps ----
  {
    id: "barbell-shrug",
    name: "Barbell Shrug",
    aliases: [],
    loadType: "barbell",
    muscles: [
      { muscle: "traps", share: 0.9 },
      { muscle: "forearms", share: 0.1 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 360,
  },
  {
    id: "dumbbell-shrug",
    name: "Dumbbell Shrug",
    aliases: [],
    loadType: "dumbbell",
    muscles: [
      { muscle: "traps", share: 0.9 },
      { muscle: "forearms", share: 0.1 },
    ],
    equipment: ["dumbbell"],
    unilateral: false,
    referenceVolume: 300,
  },
  {
    id: "face-pull",
    name: "Face Pull",
    aliases: [],
    loadType: "cable",
    muscles: [
      { muscle: "traps", share: 0.35 },
      { muscle: "shoulders", share: 0.4 },
      { muscle: "back", share: 0.25 },
    ],
    equipment: ["cable"],
    unilateral: false,
    referenceVolume: 150,
  },

  // ---- Neck ----
  {
    id: "neck-curl",
    name: "Neck Curl",
    aliases: [],
    loadType: "machine",
    muscles: [{ muscle: "neck", share: 1.0 }],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 100,
  },
  {
    id: "neck-extension",
    name: "Neck Extension",
    aliases: [],
    loadType: "machine",
    muscles: [{ muscle: "neck", share: 1.0 }],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 100,
  },

  // ---- Biceps ----
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    aliases: [],
    loadType: "barbell",
    muscles: [
      { muscle: "biceps", share: 0.85 },
      { muscle: "forearms", share: 0.15 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 180,
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell Curl",
    aliases: [],
    loadType: "dumbbell",
    muscles: [
      { muscle: "biceps", share: 0.85 },
      { muscle: "forearms", share: 0.15 },
    ],
    equipment: ["dumbbell"],
    unilateral: false,
    referenceVolume: 160,
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    aliases: [],
    loadType: "dumbbell",
    muscles: [
      { muscle: "biceps", share: 0.65 },
      { muscle: "forearms", share: 0.35 },
    ],
    equipment: ["dumbbell"],
    unilateral: false,
    referenceVolume: 160,
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    aliases: [],
    loadType: "cable",
    muscles: [
      { muscle: "biceps", share: 0.85 },
      { muscle: "forearms", share: 0.15 },
    ],
    equipment: ["cable"],
    unilateral: false,
    referenceVolume: 180,
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    aliases: [],
    loadType: "machine",
    muscles: [
      { muscle: "biceps", share: 0.9 },
      { muscle: "forearms", share: 0.1 },
    ],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 200,
  },

  // ---- Triceps ----
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    aliases: [],
    loadType: "cable",
    muscles: [
      { muscle: "triceps", share: 0.9 },
      { muscle: "forearms", share: 0.1 },
    ],
    equipment: ["cable"],
    unilateral: false,
    referenceVolume: 200,
  },
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    aliases: ["lying triceps extension"],
    loadType: "barbell",
    muscles: [
      { muscle: "triceps", share: 0.85 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["barbell", "bench"],
    unilateral: false,
    referenceVolume: 160,
  },
  {
    id: "overhead-triceps-extension",
    name: "Overhead Triceps Extension",
    aliases: [],
    loadType: "dumbbell",
    muscles: [
      { muscle: "triceps", share: 0.85 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["dumbbell"],
    unilateral: false,
    referenceVolume: 160,
  },
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    aliases: [],
    loadType: "barbell",
    muscles: [
      { muscle: "triceps", share: 0.5 },
      { muscle: "chest", share: 0.35 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["barbell", "bench"],
    unilateral: false,
    referenceVolume: 280,
  },
  {
    id: "bench-dip",
    name: "Bench Dip",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.7,
    muscles: [
      { muscle: "triceps", share: 0.6 },
      { muscle: "chest", share: 0.25 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["bench"],
    unilateral: false,
    referenceVolume: 1400,
  },

  // ---- Forearms ----
  {
    id: "wrist-curl",
    name: "Wrist Curl",
    aliases: [],
    loadType: "barbell",
    muscles: [{ muscle: "forearms", share: 1.0 }],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 100,
  },
  {
    id: "farmers-carry",
    name: "Farmer's Carry",
    aliases: ["farmer's walk"],
    loadType: "distance",
    intensityFactor: 0.5,
    muscles: [
      { muscle: "forearms", share: 0.4 },
      { muscle: "traps", share: 0.25 },
      { muscle: "abs", share: 0.15 },
      { muscle: "quads", share: 0.2 },
    ],
    equipment: ["dumbbell"],
    unilateral: false,
    referenceVolume: 1600,
  },
  {
    id: "dead-hang",
    name: "Dead Hang",
    aliases: [],
    loadType: "time",
    intensityFactor: 3,
    muscles: [
      { muscle: "forearms", share: 0.7 },
      { muscle: "back", share: 0.3 },
    ],
    equipment: ["pull-up-bar"],
    unilateral: false,
    referenceVolume: 120,
  },

  // ---- Abs ----
  {
    id: "crunch",
    name: "Crunch",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.3,
    muscles: [{ muscle: "abs", share: 1.0 }],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1400,
  },
  {
    id: "sit-up",
    name: "Sit-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.35,
    muscles: [
      { muscle: "abs", share: 0.85 },
      { muscle: "obliques", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1500,
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.55,
    muscles: [
      { muscle: "abs", share: 0.75 },
      { muscle: "obliques", share: 0.15 },
      { muscle: "quads", share: 0.1 },
    ],
    equipment: ["pull-up-bar"],
    unilateral: false,
    referenceVolume: 900,
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    aliases: [],
    loadType: "cable",
    muscles: [{ muscle: "abs", share: 1.0 }],
    equipment: ["cable"],
    unilateral: false,
    referenceVolume: 220,
  },
  {
    id: "plank",
    name: "Plank",
    aliases: [],
    loadType: "time",
    intensityFactor: 5,
    muscles: [
      { muscle: "abs", share: 0.6 },
      { muscle: "obliques", share: 0.2 },
      { muscle: "lowerBack", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 300,
  },
  {
    id: "hollow-hold",
    name: "Hollow Hold",
    aliases: [],
    loadType: "time",
    intensityFactor: 4,
    muscles: [
      { muscle: "abs", share: 0.8 },
      { muscle: "obliques", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 180,
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.5,
    muscles: [
      { muscle: "abs", share: 0.7 },
      { muscle: "obliques", share: 0.1 },
      { muscle: "lowerBack", share: 0.1 },
      { muscle: "shoulders", share: 0.1 },
    ],
    equipment: ["none"],
    unilateral: false,
    referenceVolume: 800,
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.35,
    muscles: [
      { muscle: "abs", share: 0.55 },
      { muscle: "obliques", share: 0.15 },
      { muscle: "quads", share: 0.3 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1700,
  },

  // ---- Obliques ----
  {
    id: "russian-twist",
    name: "Russian Twist",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.3,
    muscles: [
      { muscle: "obliques", share: 0.7 },
      { muscle: "abs", share: 0.3 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1200,
  },
  {
    id: "side-plank",
    name: "Side Plank",
    aliases: [],
    loadType: "time",
    intensityFactor: 4,
    muscles: [
      { muscle: "obliques", share: 0.75 },
      { muscle: "abs", share: 0.15 },
      { muscle: "shoulders", share: 0.1 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 160,
  },
  {
    id: "cable-woodchopper",
    name: "Cable Woodchopper",
    aliases: [],
    loadType: "cable",
    muscles: [
      { muscle: "obliques", share: 0.7 },
      { muscle: "abs", share: 0.2 },
      { muscle: "shoulders", share: 0.1 },
    ],
    equipment: ["cable"],
    unilateral: true,
    referenceVolume: 200,
  },

  // ---- Glutes ----
  {
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    aliases: ["hip thrust"],
    loadType: "barbell",
    muscles: [
      { muscle: "glutes", share: 0.7 },
      { muscle: "hamstrings", share: 0.2 },
      { muscle: "quads", share: 0.1 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 400,
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.35,
    muscles: [
      { muscle: "glutes", share: 0.75 },
      { muscle: "hamstrings", share: 0.25 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1500,
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    aliases: ["rear foot elevated split squat"],
    loadType: "dumbbell",
    muscles: [
      { muscle: "glutes", share: 0.4 },
      { muscle: "quads", share: 0.4 },
      { muscle: "hamstrings", share: 0.1 },
      { muscle: "abductors", share: 0.1 },
    ],
    equipment: ["dumbbell", "bench"],
    unilateral: true,
    referenceVolume: 480,
  },
  {
    id: "donkey-kick",
    name: "Donkey Kick",
    aliases: ["glute kickback"],
    loadType: "bodyweight",
    leverageFactor: 0.3,
    muscles: [
      { muscle: "glutes", share: 0.8 },
      { muscle: "hamstrings", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 1300,
  },

  // ---- Quads ----
  {
    id: "back-squat",
    name: "Back Squat",
    aliases: ["barbell squat"],
    loadType: "barbell",
    muscles: [
      { muscle: "quads", share: 0.55 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "hamstrings", share: 0.1 },
      { muscle: "lowerBack", share: 0.05 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 400,
  },
  {
    id: "front-squat",
    name: "Front Squat",
    aliases: [],
    loadType: "barbell",
    muscles: [
      { muscle: "quads", share: 0.65 },
      { muscle: "glutes", share: 0.25 },
      { muscle: "lowerBack", share: 0.1 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 320,
  },
  {
    id: "leg-press",
    name: "Leg Press",
    aliases: [],
    loadType: "machine",
    muscles: [
      { muscle: "quads", share: 0.6 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "hamstrings", share: 0.1 },
    ],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 900,
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    aliases: [],
    loadType: "machine",
    muscles: [{ muscle: "quads", share: 1.0 }],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 300,
  },
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    aliases: ["lunges"],
    loadType: "dumbbell",
    muscles: [
      { muscle: "quads", share: 0.5 },
      { muscle: "glutes", share: 0.35 },
      { muscle: "hamstrings", share: 0.1 },
      { muscle: "abductors", share: 0.05 },
    ],
    equipment: ["dumbbell"],
    unilateral: true,
    referenceVolume: 400,
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    aliases: [],
    loadType: "dumbbell",
    muscles: [
      { muscle: "quads", share: 0.55 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "hamstrings", share: 0.1 },
      { muscle: "abductors", share: 0.05 },
    ],
    equipment: ["dumbbell"],
    unilateral: false,
    referenceVolume: 240,
  },
  {
    id: "pistol-squat",
    name: "Pistol Squat",
    aliases: ["single-leg squat"],
    loadType: "bodyweight",
    leverageFactor: 0.85,
    muscles: [
      { muscle: "quads", share: 0.55 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "hamstrings", share: 0.1 },
      { muscle: "abductors", share: 0.05 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 700,
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    aliases: ["air squat"],
    loadType: "bodyweight",
    leverageFactor: 0.7,
    muscles: [
      { muscle: "quads", share: 0.55 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "hamstrings", share: 0.1 },
      { muscle: "abductors", share: 0.05 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 2400,
  },

  // ---- Hamstrings ----
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    aliases: ["rdl"],
    loadType: "barbell",
    muscles: [
      { muscle: "hamstrings", share: 0.55 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "lowerBack", share: 0.15 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 380,
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    aliases: [],
    loadType: "machine",
    muscles: [{ muscle: "hamstrings", share: 1.0 }],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 280,
  },
  {
    id: "nordic-curl",
    name: "Nordic Curl",
    aliases: ["nordic hamstring curl"],
    loadType: "bodyweight",
    leverageFactor: 0.6,
    muscles: [
      { muscle: "hamstrings", share: 0.85 },
      { muscle: "glutes", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 480,
  },
  {
    id: "glute-ham-raise",
    name: "Glute Ham Raise",
    aliases: ["ghr"],
    loadType: "bodyweight",
    leverageFactor: 0.55,
    muscles: [
      { muscle: "hamstrings", share: 0.7 },
      { muscle: "glutes", share: 0.3 },
    ],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 660,
  },

  // ---- Calves ----
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    aliases: [],
    loadType: "machine",
    muscles: [{ muscle: "calves", share: 1.0 }],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 500,
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    aliases: [],
    loadType: "machine",
    muscles: [{ muscle: "calves", share: 1.0 }],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 400,
  },
  {
    id: "bodyweight-calf-raise",
    name: "Bodyweight Calf Raise",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.35,
    muscles: [{ muscle: "calves", share: 1.0 }],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1400,
  },
  {
    id: "single-leg-calf-raise",
    name: "Single-Leg Calf Raise",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.35,
    muscles: [{ muscle: "calves", share: 1.0 }],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 1400,
  },

  // ---- Abductors / Adductors ----
  {
    id: "cable-hip-abduction",
    name: "Cable Hip Abduction",
    aliases: [],
    loadType: "cable",
    muscles: [
      { muscle: "abductors", share: 0.9 },
      { muscle: "glutes", share: 0.1 },
    ],
    equipment: ["cable"],
    unilateral: true,
    referenceVolume: 150,
  },
  {
    id: "machine-hip-abduction",
    name: "Machine Hip Abduction",
    aliases: [],
    loadType: "machine",
    muscles: [{ muscle: "abductors", share: 1.0 }],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 300,
  },
  {
    id: "cable-hip-adduction",
    name: "Cable Hip Adduction",
    aliases: [],
    loadType: "cable",
    muscles: [
      { muscle: "adductors", share: 0.9 },
      { muscle: "glutes", share: 0.1 },
    ],
    equipment: ["cable"],
    unilateral: true,
    referenceVolume: 150,
  },
  {
    id: "machine-hip-adduction",
    name: "Machine Hip Adduction",
    aliases: [],
    loadType: "machine",
    muscles: [{ muscle: "adductors", share: 1.0 }],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 300,
  },

  // ---- Full body / carries ----
  {
    id: "barbell-clean-and-press",
    name: "Clean and Press",
    aliases: [],
    loadType: "barbell",
    muscles: [
      { muscle: "shoulders", share: 0.3 },
      { muscle: "quads", share: 0.2 },
      { muscle: "glutes", share: 0.2 },
      { muscle: "traps", share: 0.2 },
      { muscle: "triceps", share: 0.1 },
    ],
    equipment: ["barbell"],
    unilateral: false,
    referenceVolume: 300,
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    aliases: ["kb swing"],
    loadType: "machine",
    muscles: [
      { muscle: "glutes", share: 0.4 },
      { muscle: "hamstrings", share: 0.3 },
      { muscle: "lowerBack", share: 0.15 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["kettlebell"],
    unilateral: false,
    referenceVolume: 240,
  },
  {
    id: "sled-push",
    name: "Sled Push",
    aliases: [],
    loadType: "distance",
    intensityFactor: 0.6,
    muscles: [
      { muscle: "quads", share: 0.4 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "hamstrings", share: 0.15 },
      { muscle: "calves", share: 0.15 },
    ],
    equipment: ["machine"],
    unilateral: false,
    referenceVolume: 960,
  },
  {
    id: "burpee",
    name: "Burpee",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.45,
    muscles: [
      { muscle: "chest", share: 0.2 },
      { muscle: "shoulders", share: 0.15 },
      { muscle: "quads", share: 0.3 },
      { muscle: "abs", share: 0.2 },
      { muscle: "glutes", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1800,
  },

  // ---- More bodyweight ----
  {
    id: "wide-grip-pushup",
    name: "Wide-Grip Push-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.66,
    muscles: [
      { muscle: "chest", share: 0.6 },
      { muscle: "triceps", share: 0.2 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 2100,
  },
  {
    id: "diamond-pushup",
    name: "Diamond Push-up",
    aliases: ["close-grip pushup", "triangle pushup"],
    loadType: "bodyweight",
    leverageFactor: 0.6,
    muscles: [
      { muscle: "triceps", share: 0.5 },
      { muscle: "chest", share: 0.35 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1700,
  },
  {
    id: "decline-pushup",
    name: "Decline Push-up",
    aliases: ["feet elevated pushup"],
    loadType: "bodyweight",
    leverageFactor: 0.74,
    muscles: [
      { muscle: "chest", share: 0.45 },
      { muscle: "shoulders", share: 0.35 },
      { muscle: "triceps", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1900,
  },
  {
    id: "archer-pushup",
    name: "Archer Push-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.7,
    muscles: [
      { muscle: "chest", share: 0.55 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 900,
  },
  {
    id: "spiderman-pushup",
    name: "Spiderman Push-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.66,
    muscles: [
      { muscle: "chest", share: 0.45 },
      { muscle: "triceps", share: 0.2 },
      { muscle: "shoulders", share: 0.15 },
      { muscle: "obliques", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1900,
  },
  {
    id: "single-arm-pushup",
    name: "Single-Arm Push-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.7,
    muscles: [
      { muscle: "chest", share: 0.55 },
      { muscle: "triceps", share: 0.3 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 350,
  },
  {
    id: "clap-pushup",
    name: "Clap Push-up",
    aliases: ["plyo pushup"],
    loadType: "bodyweight",
    leverageFactor: 0.7,
    muscles: [
      { muscle: "chest", share: 0.5 },
      { muscle: "triceps", share: 0.3 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 900,
  },
  {
    id: "jump-squat",
    name: "Jump Squat",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.75,
    muscles: [
      { muscle: "quads", share: 0.55 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "calves", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 1800,
  },
  {
    id: "sumo-squat",
    name: "Sumo Squat",
    aliases: ["wide stance squat"],
    loadType: "bodyweight",
    leverageFactor: 0.7,
    muscles: [
      { muscle: "quads", share: 0.45 },
      { muscle: "glutes", share: 0.35 },
      { muscle: "adductors", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 2300,
  },
  {
    id: "curtsy-lunge",
    name: "Curtsy Lunge",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.55,
    muscles: [
      { muscle: "glutes", share: 0.45 },
      { muscle: "quads", share: 0.35 },
      { muscle: "adductors", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 1500,
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    aliases: ["bodyweight reverse lunge"],
    loadType: "bodyweight",
    leverageFactor: 0.55,
    muscles: [
      { muscle: "quads", share: 0.5 },
      { muscle: "glutes", share: 0.35 },
      { muscle: "hamstrings", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 1600,
  },
  {
    id: "single-leg-glute-bridge",
    name: "Single-Leg Glute Bridge",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.35,
    muscles: [
      { muscle: "glutes", share: 0.8 },
      { muscle: "hamstrings", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 1300,
  },
  {
    id: "broad-jump",
    name: "Broad Jump",
    aliases: ["standing long jump"],
    loadType: "bodyweight",
    leverageFactor: 0.8,
    muscles: [
      { muscle: "quads", share: 0.45 },
      { muscle: "glutes", share: 0.35 },
      { muscle: "calves", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 700,
  },
  {
    id: "jumping-lunge",
    name: "Jumping Lunge",
    aliases: ["split jump"],
    loadType: "bodyweight",
    leverageFactor: 0.78,
    muscles: [
      { muscle: "quads", share: 0.5 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "calves", share: 0.2 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 1400,
  },
  {
    id: "high-knees",
    name: "High Knees",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.35,
    muscles: [
      { muscle: "quads", share: 0.4 },
      { muscle: "abs", share: 0.35 },
      { muscle: "calves", share: 0.25 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 2200,
  },
  {
    id: "bear-crawl",
    name: "Bear Crawl",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.45,
    muscles: [
      { muscle: "shoulders", share: 0.3 },
      { muscle: "abs", share: 0.3 },
      { muscle: "quads", share: 0.25 },
      { muscle: "chest", share: 0.15 },
    ],
    equipment: ["bodyweight"],
    unilateral: false,
    referenceVolume: 2000,
  },
  {
    id: "commando-pull-up",
    name: "Commando Pull-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 1.0,
    muscles: [
      { muscle: "back", share: 0.5 },
      { muscle: "biceps", share: 0.3 },
      { muscle: "obliques", share: 0.2 },
    ],
    equipment: ["pull-up-bar"],
    unilateral: false,
    referenceVolume: 650,
  },
  {
    id: "typewriter-pull-up",
    name: "Typewriter Pull-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 1.0,
    muscles: [
      { muscle: "back", share: 0.45 },
      { muscle: "biceps", share: 0.35 },
      { muscle: "shoulders", share: 0.2 },
    ],
    equipment: ["pull-up-bar"],
    unilateral: true,
    referenceVolume: 500,
  },
  {
    id: "muscle-up",
    name: "Muscle-up",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 1.0,
    muscles: [
      { muscle: "back", share: 0.35 },
      { muscle: "chest", share: 0.25 },
      { muscle: "triceps", share: 0.25 },
      { muscle: "shoulders", share: 0.15 },
    ],
    equipment: ["pull-up-bar"],
    unilateral: false,
    referenceVolume: 550,
  },
  {
    id: "shrimp-squat",
    name: "Shrimp Squat",
    aliases: [],
    loadType: "bodyweight",
    leverageFactor: 0.8,
    muscles: [
      { muscle: "quads", share: 0.5 },
      { muscle: "glutes", share: 0.3 },
      { muscle: "hamstrings", share: 0.15 },
      { muscle: "adductors", share: 0.05 },
    ],
    equipment: ["bodyweight"],
    unilateral: true,
    referenceVolume: 600,
  },
];

const CATALOG_BY_ID: Map<string, Exercise> = new Map(
  EXERCISE_CATALOG.map((exercise) => [exercise.id, exercise])
);

export function getExercise(id: string): Exercise | undefined {
  return CATALOG_BY_ID.get(id);
}

export function requireExercise(id: string): Exercise {
  const exercise = CATALOG_BY_ID.get(id);
  if (!exercise) {
    throw new Error(`Unknown exercise id: ${id}`);
  }
  return exercise;
}
